#Motd text (uses vanilla system, use this tool https://mctools.org/motd-creator), You can also use the normal vannila color codes. They are located here (https://minecraft.wiki/w/Formatting_codes)
motd: "             <gradient:#FFAA00:#FF00AA>⸻ RealVanilla Vanilla ⸻</gradient>"
# From here remove # if you want to use a feature

#Potho link (use this if you want to change the photo at the same time as the server is running)

#link-to-photo: link

#If you want to change the max player count, (Only visual, not changing your player count)
#max-player-count: 420

#If you want to change the current player count, (Only visual)
#player-count: 69

#Hover text for player amount, max 12, (Only visual)
#plyer-list:
  #- steve



